apiVersion: v1
kind: Service
metadata:
  name: rng-svc
  labels:
    app: rng
    tier: backend
spec:
  type: NodePort 
  # type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: rng
    tier: backend

