apiVersion: apps/v1beta2 # use apps/v1 for > 1.9.0 
kind: Deployment
metadata:
  name: rng-deploy
spec:
  selector:
    matchLabels:
      app: rng
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: rng
        tier: backend
    spec:
      containers:
      - name: rng-microsvc
        image: devopz/random-microservice
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 250m
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000

